name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: List files in root directory
      run: dir
    - name: Change to project directory and list files
      run: |
        cd HelloWorld
        dir
    - name: Restore dependencies
      run: |
        cd HelloWorld
        dotnet restore
    - name: Build
      run: |
        cd HelloWorld
        dotnet build --configuration Release --no-restore
    - name: Verify .NET SDK version
      run: dotnet --version

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Change to project directory and list files
      run: |
        cd HelloWorld
        dir
    - name: Run unit tests
      run: |
        cd HelloWorld
        dotnet test --no-build --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
    - name: Deploy to staging
      run: echo "Deploying to staging environment"
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port:  ${{ secrets.SMTP_PORT }}
        # user credentials
        username: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASSWORD }}
        # email subject
        subject: ${{ github.repository }} was a ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} was a ${{ job.status }}
        # comma-separated string, send email to
        to: jancke645@gmail.com
        # from email name
        from: Jancke du toit
      

  

    