#update to force re-fetch of latest versions
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
    - name: Deploy to staging
      run: echo "Deploying to staging environment"
    - name: Notify Success
      if: success()
      run: bash ./send-email.sh "your-team@example.com" "Deployment Success" "The deployment was successful. Check the GitHub Actions for more details."
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }} 
    - name: Notify Failure
      if: failure()
      run: bash ./send-email.sh "your-team@example.com" "Deployment Failure" "The deployment has failed. Please check the GitHub Actions for more details."
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}