name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: List files in root directory
      run: dir
    - name: Change to project directory and list files
      run: |
        cd HelloWorld
        dir
    - name: Restore dependencies
      run: |
        cd HelloWorld
        dotnet restore
    - name: Build
      run: |
        cd HelloWorld
        dotnet build --configuration Release --no-restore
    - name: Verify .NET SDK version
      run: dotnet --version

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Change to project directory and list files
      run: |
        cd HelloWorld
        dir
    - name: Run unit tests
      run: |
        cd HelloWorld
        dotnet test --no-build --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
    - name: Deploy to staging
      run: echo "Deploying to staging environment"
    - name: Notify Success
      if: success()
      run: bash .github/workflows/scripts/send-email.sh "jancke645@gmail.com" "Deployment Success" "The deployment was successful."

      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
    - name: Notify Failure
      if: failure()
      run: bash .github/workflows/scripts/send-email.sh "jancke645@gmail.com" "Deployment Failure" "The deployment has failed. "


      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
